on:
  push:
    branches:
      - refs/tags/*
name: Build framework
jobs:
  static:
    name: Build static SDK
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          mkdir -p frameworks/static
          xcodebuild -target AdjustStatic -configuration Release clean build

          mkdir AdjustSdkStatic
          mv frameworks/static/* AdjustSdkStatic
          zip -ry AdjustSdkStatic.framework.zip AdjustSdkStatic/*
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: static_framework
          path: AdjustSdkStatic.framework.zip
  tvOS:
    name: Build Static tvOS SDK
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Universal tvOS SDK
        run: |
          mkdir -p frameworks/static_tvos
          xcodebuild -configuration Release -target AdjustSdkTv -arch x86_64 -sdk appletvsimulator clean build
          xcodebuild -configuration Release -target AdjustSdkTv -arch arm64 -sdk appletvos build
          cp -Rv build/Release-appletvos/AdjustSdkTv.framework frameworks/static_tvos
          lipo -create -output frameworks/static_tvos/AdjustSdkTv.framework/AdjustSdkTv build/Release-appletvos/AdjustSdkTv.framework/AdjustSdkTv build/Release-appletvsimulator/AdjustSdkTv.framework/AdjustSdkTv

          mkdir AdjustSdkTvStatic
          mv frameworks/static_tvos/* AdjustSdkTvStatic
          zip -ry AdjustSdkTvStatic.framework.zip AdjustSdkTvStatic/*
      - name: Upload files
        uses: actions/upload-artifact@v2
        with:
          name: universal_tvos
          path: AdjustSdkTvStatic.framework.zip

  dynamic_ios_tvos:
    name: Build dynamic iOS and tvOS targets with Carthage
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Carthage
        run: |
          brew install carthage
      - name: Build dynamic framework
        run: |
          mv Adjust.xcodeproj/xcshareddata/xcschemes/AdjustSdkIm.xcscheme \
            Adjust.xcodeproj/xcshareddata/xcschemes/AdjustSdkWebBridge.xcscheme .
          carthage build --no-skip-current
          
          mkdir AdjustSdkDynamic
          mv Carthage/Build/iOS/* AdjustSdkDynamic
          zip -ry AdjustSdkDynamic.framework.zip AdjustSdkDynamic/*

          mkdir AdjustSdkTvDynamic
          mv Carthage/Build/tvOS/* AdjustSdkTvDynamic
          zip -ry AdjustSdkTvDynamic.framework.zip AdjustSdkTvDynamic/*
      - name: Upload iOS
        uses: actions/upload-artifact@v2
        with:
          name: dynamic_ios
          path: AdjustSdkDynamic.framework.zip
      - name: Upload tvOS
        uses: actions/upload-artifact@v2
        with:
          name: dynamic_tvos
          path: AdjustSdkTvDynamic.framework.zip

  dynamic_imessage:
    name: Build dynamic iMessage target with Carthage
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Carthage
        run: |
          brew install carthage
      - name: Build dynamic framework
        run: |
          mv Adjust.xcodeproj/xcshareddata/xcschemes/*.xcscheme .
          mv AdjustSdkIm.xcscheme Adjust.xcodeproj/xcshareddata/xcschemes

          carthage build --no-skip-current
          
          mkdir AdjustSdkImDynamic
          mv Carthage/Build/iOS/* AdjustSdkImDynamic
          zip -ry AdjustSdkIm.framework.zip AdjustSdkImDynamic/*
      - name: Upload framework
        uses: actions/upload-artifact@v2
        with:
          name: dynamic_imessage
          path: AdjustSdkIm.framework.zip

  dynamic_webbridge:
    name: Build dynamic WebBridge target with Carthage
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Carthage
        run: |
          brew install carthage
      - name: Build dynamic framework
        run: |
          mv Adjust.xcodeproj/xcshareddata/xcschemes/*.xcscheme .
          mv AdjustSdkWebBridge.xcscheme Adjust.xcodeproj/xcshareddata/xcschemes

          carthage build --no-skip-current
          mkdir AdjustSdkWebBridgeDynamic
          mv Carthage/Build/iOS/* AdjustSdkWebBridgeDynamic
          zip -ry AdjustSdkWebBridge.framework.zip AdjustSdkWebBridgeDynamic/*
      - name: Upload framework
        uses: actions/upload-artifact@v2
        with:
          name: dynamic_webbridge
          path: AdjustSdkWebBridge.framework.zip

  release:
    name: Create new release and upload assets
    runs-on: ubuntu-latest
    needs: [static, tvOS, dynamic_ios_tvos, dynamic_imessage, dynamic_webbridge]
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Version ${{ github.ref }}
          draft: true
          prerelease: false

      - name: Download all frameworks
        uses: actions/download-artifact@v2
        with:
          path: frameworks
          
      - name: Upload static framework
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: frameworks/static_framework/AdjustSdkStatic.framework.zip
          asset_name: AdjustSdkStatic.framework.zip
          asset_content_type: application/zip
          
      - name: Upload tvOS framework
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: frameworks/universal_tvos/AdjustSdkTvStatic.framework.zip
          asset_name: AdjustSdkTvStatic.framework.zip
          asset_content_type: application/zip
          
      - name: Upload dynamic iOS framework
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: frameworks/dynamic_ios/AdjustSdkDynamic.framework.zip
          asset_name: AdjustSdkDynamic.framework.zip
          asset_content_type: application/zip
          
      - name: Upload dynamic tvOS framework
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: frameworks/dynamic_tvos/AdjustSdkTvDynamic.framework.zip
          asset_name: AdjustSdkTvDynamic.framework.zip
          asset_content_type: application/zip
          
      - name: Upload dynamic iMessage framework
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: frameworks/dynamic_imessage/AdjustSdkIm.framework.zip
          asset_name: AdjustSdkIm.framework.zip
          asset_content_type: application/zip
          
      - name: Upload dynamic WebBridge framework
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} 
          asset_path: frameworks/dynamic_webbridge/AdjustSdkWebBridge.framework.zip
          asset_name: AdjustSdkWebBridge.framework.zip
          asset_content_type: application/zip

